version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_ENV=development
    command: python api.py

  ui:
    build: ./ui
    volumes:
      - ./ui:/usr/share/nginx/html
    ports:
      - "8080:80"